"""add merchant_id to stores

Revision ID: a4dda187b950
Revises: d53fc5b6be01
Create Date: 2026-04-11 22:00:49.101211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4dda187b950'
down_revision = 'd53fc5b6be01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['merchant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('merchant_id')

    # ### end Alembic commands ###
