/**
 * Feature: Merchant Reports
 * Branch: feature/merchant-reports
 * Changes for new store_products junction table: reports now aggregate across store_products
 */

import React, { useState, useEffect } from 'react';
import DashboardLayout from '../../components/layout/DashboardLayout';
import { toast } from 'react-toastify';
import api from '../../utils/api';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line } from 'recharts';

const MerchantReports = () => {
  const [summary, setSummary] = useState({});
  const [trendData, setTrendData] = useState([]);
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    fetchReports();
  }, [startDate, endDate]);

  const fetchReports = async () => {
    try {
      let url = '/inventory/report/summary';
      if (startDate) url += `?start_date=${startDate}`;
      if (endDate) url += `&end_date=${endDate}`;

      const res = await api.get(url);
      setSummary(res.data.summary || {});

      const trendRes = await api.get('/inventory/report/trend');
      setTrendData(trendRes.data.trend || []);
    } catch {
      toast.error('Failed to load reports');
    }
  };

  const exportToPDF = async () => {
    setExporting(true);
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();

      pdf.setFontSize(18);
      pdf.text("Inventory App", pageWidth / 2, 20, { align: 'center' });

      pdf.setFontSize(11);
      pdf.text(`Generated by: Merchant`, 20, 35);
      pdf.text(`Email: ${localStorage.getItem('userEmail') || ''}`, 20, 42);
      pdf.text(`Phone: ${localStorage.getItem('userPhone') || ''}`, 20, 49);
      pdf.text(`Role: Merchant`, 20, 56);
      pdf.text(`Date Range: ${startDate || 'All'} - ${endDate || 'All'}`, 20, 63);

      pdf.setFontSize(16);
      pdf.text("Merchant Performance Report", pageWidth / 2, 80, { align: 'center' });

      pdf.setFontSize(12);
      pdf.text(`Total Received : ${summary.total_items_received || 0}`, 20, 95);
      pdf.text(`In Stock       : ${summary.total_items_in_stock || 0}`, 20, 102);
      pdf.text(`Spoilt         : ${summary.total_items_spoilt || 0}`, 20, 109);

      const chartElement = document.getElementById('report-charts');
      if (chartElement) {
        const canvas = await html2canvas(chartElement, { scale: 2 });
        const imgData = canvas.toDataURL('image/png');
        pdf.addImage(imgData, 'PNG', 20, 120, 170, 95);
      }

      pdf.save(`Merchant_Report_${new Date().toISOString().slice(0,10)}.pdf`);
      toast.success('Report exported to PDF');
    } catch (err) {
      toast.error('Failed to generate PDF');
    } finally {
      setExporting(false);
    }
  };

  return (
    <DashboardLayout title="Reports 📈">
      <div className="card">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
          <div>
            <label className="block text-sm font-medium mb-1">From Date</label>
            <input type="date" className="input-field" value={startDate} onChange={(e) => setStartDate(e.target.value)} />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">To Date</label>
            <input type="date" className="input-field" value={endDate} onChange={(e) => setEndDate(e.target.value)} />
          </div>
          <button onClick={exportToPDF} disabled={exporting} className="btn-primary h-10 mt-6">
            {exporting ? 'Exporting...' : 'Export to PDF'}
          </button>
        </div>
      </div>

      <div id="report-charts" className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="card">
          <h3 className="text-lg font-semibold mb-4">Store Performance</h3>
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={trendData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="product_name" />
              <YAxis />
              <Tooltip />
              <Bar dataKey="quantity_received" fill="#4F46E5" />
              <Bar dataKey="quantity_in_stock" fill="#10B981" />
            </BarChart>
          </ResponsiveContainer>
        </div>

        <div className="card">
          <h3 className="text-lg font-semibold mb-4">Trend Over Time</h3>
          <ResponsiveContainer width="100%" height={300}>
            <LineChart data={trendData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="product_name" />
              <YAxis />
              <Tooltip />
              <Line type="monotone" dataKey="quantity_received" stroke="#4F46E5" strokeWidth={3} />
              <Line type="monotone" dataKey="quantity_in_stock" stroke="#10B981" strokeWidth={3} />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>
    </DashboardLayout>
  );
};

export default MerchantReports;
