import React, { useState, useEffect, useCallback } from 'react';
import DashboardLayout from '../../components/layout/DashboardLayout';
import { toast } from 'react-toastify';
import api from '../../utils/api';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import StatCard from '../../components/common/StatCard';
import Chart from '../../components/common/Chart';

const MerchantReports = () => {
  const [summary, setSummary] = useState({});
  const [trendData, setTrendData] = useState([]);
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [exporting, setExporting] = useState(false);

  const fetchReports = useCallback(async () => {
    try {
      let url = '/inventory/report/summary';
      if (startDate) url += `?start_date=${startDate}`;
      if (endDate) url += `&end_date=${endDate}`;

      const res = await api.get(url);
      setSummary(res.data.summary || {});

      const trendRes = await api.get('/inventory/report/trend');
      const cleaned = (trendRes.data.trend || []).map(item => ({
        ...item,
        quantity_received: Number(item.quantity_received) || 0,
        quantity_in_stock: Number(item.quantity_in_stock) || 0,
      }));
      setTrendData(cleaned);
    } catch {
      toast.error('Failed to load reports');
    }
  }, [startDate, endDate]);

  useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  const exportToPDF = async () => {
    setExporting(true);
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();

      pdf.setFontSize(18);
      pdf.text("Inventory App", pageWidth / 2, 20, { align: 'center' });

      pdf.setFontSize(11);
      pdf.text(`Generated by: Merchant`, 20, 35);
      pdf.text(`Date: ${new Date().toLocaleDateString()}`, 20, 42);

      const chartElement = document.getElementById('report-charts');
      if (chartElement) {
        const canvas = await html2canvas(chartElement, { scale: 2 });
        const imgData = canvas.toDataURL('image/png');
        pdf.addImage(imgData, 'PNG', 15, 55, 180, 110);
      }

      pdf.save(`Merchant_Report_${new Date().toISOString().slice(0,10)}.pdf`);
      toast.success('PDF exported successfully');
    } catch (err) {
      toast.error('Failed to generate PDF');
    } finally {
      setExporting(false);
    }
  };

  return (
    <DashboardLayout title="Reports 📈">
      {/* Filter Section  */}
      <div className="bg-white dark:bg-gray-900 rounded-2xl shadow-sm p-5 mb-4">
        <div className="flex flex-wrap items-end gap-4">
          <div>
            <label className="block text-sm font-medium mb-1">From Date</label>
            <input
              type="date"
              className="input-field"
              value={startDate}
              onChange={(e) => setStartDate(e.target.value)}
            />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">To Date</label>
            <input
              type="date"
              className="input-field"
              value={endDate}
              onChange={(e) => setEndDate(e.target.value)}
            />
          </div>
          <button
            onClick={exportToPDF}
            disabled={exporting}
            className="btn-primary px-8 py-2.5"
          >
            {exporting ? 'Exporting...' : 'Export to PDF'}
          </button>
        </div>
      </div>

      {/* Summary Stats  */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-6">
        <StatCard title="Total Received" value={summary.total_items_received || 0} icon="📥" color="bg-blue-500" />
        <StatCard title="In Stock" value={summary.total_items_in_stock || 0} icon="📦" color="bg-green-500" />
        <StatCard title="Spoilt" value={summary.total_items_spoilt || 0} icon="⚠️" color="bg-red-500" />
        <StatCard title="Unpaid (KES)" value={`KES ${(summary.total_unpaid_amount || 0).toLocaleString()}`} icon="💰" color="bg-orange-500" />
      </div>

      {/* Charts  */}
      <div id="report-charts" className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        <Chart
          title="Store Performance"
          data={trendData}
          dataKey1="quantity_received"
          dataKey2="quantity_in_stock"
          name1="Received"
          name2="In Stock"
          color1="#4F46E5"
          color2="#10B981"
          type="bar"
          xDataKey="product_name"
        />

        <Chart
          title="Trend Over Time"
          data={trendData}
          dataKey1="quantity_received"
          dataKey2="quantity_in_stock"
          name1="Received"
          name2="In Stock"
          color1="#4F46E5"
          color2="#10B981"
          type="line"
          xDataKey="product_name"
        />
      </div>
    </DashboardLayout>
  );
};

export default MerchantReports;