import React, { useState, useEffect, useCallback } from 'react';
import DashboardLayout from '../../components/layout/DashboardLayout';
import { toast } from 'react-toastify';
import api from '../../utils/api';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  LineChart, Line, LabelList 
} from 'recharts';

const MerchantReports = () => {
  const [summary, setSummary] = useState({});
  const [trendData, setTrendData] = useState([]);
  const [stores, setStores] = useState([]);
  const [selectedStoreId, setSelectedStoreId] = useState('');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [exporting, setExporting] = useState(false);

  const fetchStores = useCallback(async () => {
    try {
      const res = await api.get('/stores/');
      setStores(res.data.stores || []);
    } catch (err) {
      console.error('Failed to load stores');
    }
  }, []);

  const fetchReports = useCallback(async () => {
    try {
      let url = `/inventory/report/summary`;
      const params = [];
      if (selectedStoreId) params.push(`store_id=${selectedStoreId}`);
      if (startDate) params.push(`start_date=${startDate}`);
      if (endDate) params.push(`end_date=${endDate}`);
      if (params.length) url += `?${params.join('&')}`;

      const res = await api.get(url);
      setSummary(res.data.summary || {});

      // Trend (safe fallback if 404)
      try {
        const trendRes = await api.get('/inventory/report/trend');
        setTrendData(trendRes.data.trend || []);
      } catch {
        setTrendData([]);
      }
    } catch (err) {
      toast.error('Failed to load report data');
    }
  }, [selectedStoreId, startDate, endDate]);

  useEffect(() => {
    fetchStores();
    fetchReports();
  }, [fetchStores, fetchReports]);

  const exportToPDF = async () => {
    setExporting(true);
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();

      pdf.setFontSize(18);
      pdf.text("Inventory App", pageWidth / 2, 20, { align: 'center' });

      pdf.setFontSize(11);
      pdf.text(`Generated by: ${localStorage.getItem('userFullName') || 'Merchant'}`, 20, 35);
      pdf.text(`Email: ${localStorage.getItem('userEmail') || ''}`, 20, 42);
      pdf.text(`Phone: ${localStorage.getItem('userPhone') || ''}`, 20, 49);
      pdf.text(`Role: Merchant`, 20, 56);
      pdf.text(`Date Range: ${startDate || 'All'} - ${endDate || 'All'}`, 20, 63);
      pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 70);

      pdf.setFontSize(16);
      pdf.text("Merchant Performance Report", pageWidth / 2, 85, { align: 'center' });

      pdf.setFontSize(12);
      pdf.text(`Total Received : ${summary.total_items_received || 0}`, 20, 100);
      pdf.text(`In Stock       : ${summary.total_items_in_stock || 0}`, 20, 107);
      pdf.text(`Spoilt         : ${summary.total_items_spoilt || 0}`, 20, 114);
      pdf.text(`Paid Amount    : KES ${(summary.total_paid_amount || 0).toLocaleString()}`, 20, 121);
      pdf.text(`Unpaid Amount  : KES ${(summary.total_unpaid_amount || 0).toLocaleString()}`, 20, 128);

      const chartElement = document.getElementById('report-charts');
      if (chartElement) {
        const canvas = await html2canvas(chartElement, { scale: 2 });
        const imgData = canvas.toDataURL('image/png');
        pdf.addImage(imgData, 'PNG', 20, 145, 170, 95);
      }

      pdf.save(`Merchant_Report_${new Date().toISOString().slice(0,10)}.pdf`);
      toast.success('✅ Report exported successfully');
    } catch (err) {
      toast.error('Failed to generate PDF');
    } finally {
      setExporting(false);
    }
  };

  return (
    <DashboardLayout title="Reports 📈">
      <div className="space-y-6">
        {/* Filters */}
        <div className="card">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">From Date</label>
              <input 
                type="date" 
                className="input-field"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">To Date</label>
              <input 
                type="date" 
                className="input-field"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Store</label>
              <select 
                className="input-field"
                value={selectedStoreId}
                onChange={(e) => setSelectedStoreId(e.target.value)}
              >
                <option value="">All Stores</option>
                {stores.map(s => (
                  <option key={s.id} value={s.id}>{s.name}</option>
                ))}
              </select>
            </div>

            <button 
              onClick={exportToPDF}
              disabled={exporting}
              className="btn-primary h-10"
            >
              {exporting ? 'Exporting...' : 'Export to PDF'}
            </button>
          </div>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <div className="card text-center">
            <p className="text-sm text-gray-500">Total Received</p>
            <p className="text-3xl font-bold mt-2">{summary.total_items_received || 0}</p>
          </div>
          <div className="card text-center">
            <p className="text-sm text-gray-500">In Stock</p>
            <p className="text-3xl font-bold mt-2 text-green-600">{summary.total_items_in_stock || 0}</p>
          </div>
          <div className="card text-center">
            <p className="text-sm text-gray-500">Spoilt</p>
            <p className="text-3xl font-bold mt-2 text-red-600">{summary.total_items_spoilt || 0}</p>
          </div>
          <div className="card text-center">
            <p className="text-sm text-gray-500">Unpaid (KES)</p>
            <p className="text-3xl font-bold mt-2 text-orange-600">
              {(summary.total_unpaid_amount || 0).toLocaleString()}
            </p>
          </div>
        </div>

        {/* Charts - Improved for PDF */}
        <div id="report-charts" className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="card">
            <h3 className="text-lg font-semibold mb-4">Store Performance</h3>
            <div className="h-80">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={trendData.length ? trendData : [{product_name: 'No Data', quantity_received: 0, quantity_in_stock: 0}]}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis 
                    dataKey="product_name" 
                    angle={-45} 
                    textAnchor="end"
                    height={80}
                    interval={0}
                    tick={{ fontSize: 11 }}
                  />
                  <YAxis />
                  <Tooltip />
                  <Bar dataKey="quantity_received" fill="#4F46E5" name="Received">
                    <LabelList dataKey="quantity_received" position="top" fontSize={10} />
                  </Bar>
                  <Bar dataKey="quantity_in_stock" fill="#10B981" name="In Stock">
                    <LabelList dataKey="quantity_in_stock" position="top" fontSize={10} />
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="card">
            <h3 className="text-lg font-semibold mb-4">Trend Over Time</h3>
            <div className="h-80">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={trendData.length ? trendData : [{product_name: 'No Data', quantity_received: 0, quantity_in_stock: 0}]}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis 
                    dataKey="product_name" 
                    angle={-45} 
                    textAnchor="end"
                    height={80}
                    interval={0}
                    tick={{ fontSize: 11 }}
                  />
                  <YAxis />
                  <Tooltip />
                  <Line type="monotone" dataKey="quantity_received" stroke="#4F46E5" strokeWidth={3} />
                  <Line type="monotone" dataKey="quantity_in_stock" stroke="#10B981" strokeWidth={3} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
};

export default MerchantReports;